name: Test build LaTeX document
on:
  pull_request:
    branches: master
    paths:
      - '**/*.tex'
      - './*.tex'
      - 'Makefile'
      - 'Dockerfile'
    workflow_dispatch:

jobs:
  build:
    name: Test build Latex document
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image and generate PDF
      run: |
        make docker
